### ISSUE TITLE
How well does python/dart interop work

### ISSUE THREAD

**Issue by refack** [emboman13/matrixbullshit#1]
I've been contemplating doing some such interop...
I was afraid it would be too soy.

How was your experience [fixed]?

**Comment by emboman13** [comment]
Wouldn't know; this was a hackathon I did with a roommate a while back. I mostly was just playing w/ neural networks and image processing for it while he did most of the hookup to dart b/c he was fiddling around with an app at the time.

**Comment by refack** [comment]
Thanks
